let S1="skipForceThemingList";
let S2="skipThemingList";
let F1="fallbackBackgroundList";
let B1="transparentZenSettings";
let S3="stylesMapping";
let L1=true;
const B2=`body::before{content:'';position:fixed;top:50%;left:50%;width:500px;height:500px;transform:translate(-50%,-50%);filter:blur(50px);background-image:url(''),linear-gradient(#4ddc9e3b,#061733,#340a20);background-size:cover;background-position:center;background-repeat:no-repeat;animation:r1 10s cubic-bezier(0.8,0.2,0.2,0.8) alternate infinite;border-radius:30% 70% 70% 30%/30% 30% 70% 70%;z-index:-1;pointer-events:none}@keyframes r1{0%{transform:translate(-50%,-50%) rotate(0deg)}100%{transform:translate(-50%,-50%) rotate(360deg)}}`;
const C1=new Map();
const A1=new Map();
const S4=new Map();
const I1={48:"assets/images/logo_48.png",96:"assets/images/logo_96.png"};
const I2={48:"assets/images/logo-off_48.png",96:"assets/images/logo-off_96.png"};
const D1={enableStyling:true,autoUpdate:true,forceStyling:true,whitelistMode:false,whitelistStyleMode:false,disableTransparency:false,disableHover:true,disableFooter:true,fallbackBackgroundList:[]};
function N1(h){return h.startsWith("www.")?h.substring(4):h;}
function E1(s={}){const r={...s};for(const[k,v]of Object.entries(D1)){if(r[k]===undefined)r[k]=v;}return r;}
function shouldApplyStyling(h,c){const k=`styling:${h}`;if(S4.has(k))return c(S4.get(k));const n=N1(h);chrome.storage.local.get(B1,d=>{const s=E1(d[B1]||{});if(!s.enableStyling){const r={shouldApply:false,reason:"globally_disabled"};S4.set(k,r);return c(r);}if(C1.size===0){preloadStyles(()=>shouldApplyStyling(h,c));return;}let hs=false;if(C1.has(n)||C1.has(`www.${n}`)){hs=true;}else{for(const cs of C1.keys()){if(cs.startsWith("+")){const bs=cs.slice(1);if(n===bs||n.endsWith(`.${bs}`)){hs=true;break;}}else if(cs.startsWith("-")){const bs=cs.slice(1);const cd=bs.split(".").slice(0,-1).join(".");const hp=n.split(".");const hd=hp.length>1?hp.slice(0,-1).join("."):n;if(cd&&hd&&hd===cd){hs=true;break;}}else if(n!==cs&&n.endsWith(`.${cs}`)&&!cs.startsWith("-")){hs=true;break;}}}chrome.storage.local.get([S3,S2,S1],d2=>{if(!hs){const md=d2[S3];if(md&&md.mapping){for(const ts of Object.values(md.mapping)){if(ts.includes(n)){hs=true;break;}}}}if(hs){const sl=d2[S2]||[];const sm=s.whitelistStyleMode||false;let sa,re;if(sm){sa=sl.includes(n);re=sa?"whitelisted":"not_whitelisted";}else{sa=!sl.includes(n);re=sa?"not_blacklisted":"blacklisted";}const r={shouldApply:sa,reason:re};S4.set(k,r);return c(r);}if(s.forceStyling){const sf=d2[S1]||[];const wm=s.whitelistMode||false;let sa,re;if(wm){sa=sf.includes(n);re=sa?"force_whitelisted":"force_not_whitelisted";}else{sa=!sf.includes(n);re=sa?"force_not_blacklisted":"force_blacklisted";}const r={shouldApply:sa,reason:re};S4.set(k,r);return c(r);}const r={shouldApply:false,reason:"no_styling_rules"};S4.set(k,r);c(r);});});}
function updateIconForTab(t,u){const up=tu=>{if(!tu||!tu.startsWith("http"))return setIcon(t,false);const uo=new URL(tu);const h=uo.hostname;shouldApplyStyling(h,st=>{setIcon(t,st.shouldApply);if(L1)console.log(`Icon updated for ${h}: styling ${st.shouldApply?"ON":"OFF"} (${st.reason})`);});};if(u)up(u);else chrome.tabs.get(t,tb=>{if(tb)up(tb.url);});}
function setIcon(t,e){const i=e?I1:I2;chrome.browserAction.setIcon({path:i,tabId:t});}
function preloadStyles(c){chrome.storage.local.get(["styles",B1,S3],d=>{const s=E1(d[B1]||{});if(JSON.stringify(s)!==JSON.stringify(d[B1])){if(L1)console.log("Missing settings detected, applying defaults:",s);chrome.storage.local.set({[B1]:s});}if(s.enableStyling===false){if(c)c();return;}C1.clear();if(d.styles&&d.styles.website){for(const[w,f]of Object.entries(d.styles.website)){let cc="";for(const cs of Object.values(f)){cc+=cs+"\n";}const wk=w.replace(".css","");C1.set(wk,cc);}if(L1)console.log("Styles preloaded for faster injection");}if(c)c();});}
chrome.webNavigation.onBeforeNavigate.addListener(d=>{if(d.frameId===0){A1.set(d.tabId,d.url);updateIconForTab(d.tabId,d.url);}});
chrome.runtime.onMessage.addListener((m,s,r)=>{if(m.action==="contentScriptReady"&&m.hostname){return true;}else if(m.action==="enableAutoUpdate"){startAutoUpdate();}else if(m.action==="disableAutoUpdate"){stopAutoUpdate();}else if(m.action==="contentScriptReady"&&s.tab){updateIconForTab(s.tab.id,s.tab.url);}else if(m.action==="reapplyStyles"&&m.tabId){chrome.tabs.get(m.tabId,t=>{if(t){chrome.tabs.sendMessage(t.id,{action:"applyStyles",css:""},()=>{if(chrome.runtime.lastError){}applyCSSToTab(t);});}});}});
function getStylesForHostname(h,s,c){s=E1(s);if(C1.has(h))return c(C1.get(h));if(C1.has(`www.${h}`))return c(C1.get(`www.${h}`));for(const[cs,cc]of C1.entries()){if(cs.startsWith("+")){const bs=cs.slice(1);if(h===bs||h.endsWith(`.${bs}`))return c(cc);}else if(cs.startsWith("-")){const bs=cs.slice(1);const cd=bs.split(".").slice(0,-1).join(".");const hp=h.split(".");const hd=hp.length>1?hp.slice(0,-1).join("."):h;if(cd&&hd&&hd===cd)return c(cc);}else if(h!==cs&&h.endsWith(`.${cs}`)&&!cs.startsWith("-")){return c(cc);}}chrome.storage.local.get([S3,S1],d=>{const md=d[S3];if(md&&md.mapping){for(const[ss,ts]of Object.entries(md.mapping)){if(ts.includes(h)){const sk=ss.replace(".css","");if(C1.has(sk))return c(C1.get(sk));}}}if(s.forceStyling){const sl=d[S1]||[];const wm=s.whitelistMode||false;const si=sl.includes(h);if((wm&&si)||(!wm&&!si)){return c(C1.get("example.com")||"");}}c(null);});}
function applyCSSToTab(t){if(!t||!t.url||!t.url.startsWith("http"))return;const u=new URL(t.url);const h=N1(u.hostname);shouldApplyStyling(h,st=>{setIcon(t.id,st.shouldApply);if(st.reason==="globally_disabled")return;chrome.storage.local.get([B1,F1,"styles",S3],d=>{const fl=d[F1]||[];const hf=fl.includes(h);if(hf){let c=`html{background-color:light-dark(#fff,#111);}`;chrome.tabs.insertCSS(t.id,{code:c,runAt:"document_start"});return;}if(st.shouldApply){const gs=E1(d[B1]||{});getStylesForHostname(h,gs,c=>{if(c){applyFinalCSS(t.id,h,c);}});}});});}
function applyFinalCSS(t,h,c){chrome.storage.local.get([B1,`transparentZenSettings.${N1(h)}`],d=>{const gs=E1(d[B1]||{});if(c.trim()){const fc=B2+"\n"+c;chrome.tabs.sendMessage(t,{action:"applyStyles",css:fc},r=>{if(chrome.runtime.lastError){chrome.tabs.insertCSS(t,{code:fc,runAt:"document_start"});}});}});}
chrome.tabs.onUpdated.addListener((t,c,tb)=>{if(c.status==="complete"){updateIconForTab(t,tb.url);}});
chrome.tabs.onActivated.addListener(a=>{updateIconForTab(a.tabId);});
chrome.storage.onChanged.addListener((c,a)=>{if(a==="local"&&(c[B1]||c[S2]||c[S1]||c[S3])){S4.clear();if(L1)console.log("Cleared styling state cache due to settings change");}});
let A2;
function startAutoUpdate(){if(A2)clearInterval(A2);A2=setInterval(refetchCSS,2*60*60*1000);}
function stopAutoUpdate(){if(A2)clearInterval(A2);}
function refetchCSS(){chrome.storage.local.get("stylesRepositoryUrl",rd=>{const dr="https://sameerasw.github.io/my-internet/styles.json";const ru=rd.stylesRepositoryUrl||dr;fetch(ru,{headers:{"Cache-Control":"no-cache"}}).then(r=>{if(!r.ok)throw new Error(`Failed to fetch styles (Status: ${r.status})`);return r.json();}).then(st=>{chrome.storage.local.get([S3,B1],d=>{let md=st.mapping&&Object.keys(st.mapping).length>0?{mapping:st.mapping}:d[S3]||{mapping:{}};let s=d[B1]||{};s.lastFetchedTime=Date.now();chrome.storage.local.set({styles:st,[S3]:md,[B1]:s},()=>{console.info(`All styles refetched and updated from ${ru}`);preloadStyles();});});}).catch(e=>console.error("Error refetching styles:",e));});}
function initializeExtension(){chrome.storage.local.get(null,d=>{const s=E1(d[B1]||{});const ts={};let nu=false;if(JSON.stringify(s)!==JSON.stringify(d[B1])){ts[B1]=s;nu=true;}if(!d[S1]){ts[S1]=[];nu=true;}if(!d[S2]){ts[S2]=[];nu=true;}if(!d[F1]){ts[F1]=[];nu=true;}if(!d[S3]){ts[S3]={mapping:{}};nu=true;}if(nu){chrome.storage.local.set(ts);}preloadStyles(()=>{if(s.autoUpdate){startAutoUpdate();}chrome.tabs.query({},tbs=>{for(const t of tbs){updateIconForTab(t.id,t.url);}});});});}
chrome.webNavigation.onCommitted.addListener(d=>{if(d.frameId===0){chrome.tabs.get(d.tabId,t=>{if(t)applyCSSToTab(t);});}});
initializeExtension();
